"""Legal page generator with versioning (spec §76, §78).

Pages are assembled from the live system (business profile, data registry,
provider registry, tracking registry, subscription terms) - not stale
boilerplate. Every page is a DRAFT until a human reviewer signs it off, and a
material change to published terms records whether notice or new consent is
needed before it takes effect.
"""

from __future__ import annotations

import datetime as dt
import difflib
import hashlib
import sys
from pathlib import Path
from typing import Any

from .home import bau_home
from .store import JsonlStore, YamlStore

PAGES = ["terms_of_service", "privacy_policy", "cookie_policy", "ai_disclosure",
         "refund_policy", "cancellation_policy", "acceptable_use", "licensing", "ip_notice",
         "dmca_process", "accessibility_statement", "contact", "data_rights_process",
         "subprocessors", "security_disclosure"]
MATERIAL_SECTIONS = {"price", "billing", "renewal", "cancellation", "data use", "sharing",
                     "arbitration", "liability", "ai", "fees"}
DRAFT_BANNER = ("> DRAFT generated by BAU from live system data. It is not legal advice and "
                "must be reviewed by qualified counsel before publication.\n\n")


def _section(title: str, body: str) -> str:
    return f"## {title}\n\n{body.strip()}\n\n"


def render(page: str, profile: dict[str, Any], data_objects: list[dict[str, Any]],
           providers: list[dict[str, Any]], tracking: list[dict[str, Any]]) -> str:
    """Build page text. Unknown facts are left as visible [[TO FILL]] markers."""
    if page not in PAGES:
        raise ValueError(f"page must be one of {PAGES}")
    name = profile.get("legal_name", "[[TO FILL: legal entity name]]")
    contact = profile.get("contact_email", "[[TO FILL: contact email]]")
    address = profile.get("postal_address", "[[TO FILL: postal address]]")
    out = f"# {page.replace('_', ' ').title()} - {name}\n\n"
    if page == "privacy_policy":
        cats = sorted({d["category"] for d in data_objects}) or ["[[TO FILL]]"]
        purposes = sorted({d["purpose"] for d in data_objects}) or ["[[TO FILL]]"]
        out += _section("Who we are", f"{name}, {address}. Contact: {contact}.")
        out += _section("Data we collect", "\n".join(f"- {c}" for c in cats))
        out += _section("Why we use it (data use)", "\n".join(f"- {p}" for p in purposes))
        out += _section("Retention", "\n".join(
            f"- {d['category']}: {d['retention_days']} days" for d in data_objects)
            or "[[TO FILL]]")
        out += _section("Who we share it with (sharing)", "\n".join(
            f"- {p['provider_id']} ({p.get('jurisdiction', '?')})" for p in providers)
            or "No third parties.")
        out += _section("Your rights", "Access, correction, deletion, portability, opt-out "
                        "of sale/sharing and targeted advertising, and appeal, where your law "
                        f"provides them. Use {profile.get('dsr_url', '[[TO FILL: request form]]')}"
                        " or email " + contact + ". We do not sell personal data unless this "
                        "page says otherwise.")
        out += _section("AI", "Where we use AI to generate content or interact with you, we "
                        "say so at the point you see it.")
    elif page == "cookie_policy":
        def line(t: dict[str, Any]) -> str:
            need = "strictly necessary" if t["strictly_necessary"] else \
                "optional - you can refuse or withdraw"
            return (f"- **{t['name']}** ({t['kind']}): {t['purpose']}; recipient "
                    f"{t['recipient']}; kept {t['retention_days']} days; {need}")
        rows = "\n".join(line(t) for t in tracking) or "We use no cookies or trackers."
        out += _section("What we use", rows)
    elif page == "ai_disclosure":
        out += _section("How we use AI", profile.get("ai_use", "[[TO FILL: describe AI use]]"))
        out += _section("Labels", "AI-generated or AI-altered images, video, audio and "
                        "synthetic performers are labelled where you see them, and carry "
                        "machine-readable provenance where the technology supports it.")
    elif page in ("cancellation_policy", "refund_policy"):
        sub = profile.get("subscription", {})
        out += _section("Price, billing and renewal", sub.get(
            "terms", "[[TO FILL: price, billing frequency, renewal and trial terms]]"))
        out += _section("How to cancel", sub.get(
            "cancel", "Cancel online any time from your account page - the same way you "
                      "signed up. Cancellation takes effect immediately for future charges "
                      "and we email a confirmation."))
        out += _section("Refunds", profile.get("refunds", "[[TO FILL: refund terms]]"))
    elif page == "accessibility_statement":
        out += _section("Our commitment", "We aim to meet WCAG 2.2 level AA. Every critical "
                        "function works with a keyboard alone.")
        out += _section("Feedback", f"Tell us about barriers at {contact}.")
    elif page == "subprocessors":
        out += _section("Subprocessors", "\n".join(
            f"- {p['provider_id']}: {', '.join(p.get('data_sent', [])) or 'see contract'}"
            for p in providers) or "None.")
    elif page == "contact":
        out += _section("Contact", f"{name}\n{address}\n{contact}")
    else:
        out += _section("Content", profile.get(page, f"[[TO FILL: {page} text]]"))
    return out


class LegalPages:
    def __init__(self, home: Path | None = None):
        base = (home or bau_home()) / "compliance" / "legal_pages"
        self.versions = JsonlStore(base / "versions.jsonl")
        self.profile = YamlStore((home or bau_home()) / "config" / "business_profile.yaml")

    def latest(self, page: str, published_only: bool = False) -> dict[str, Any] | None:
        found = None
        for v in self.versions:
            if v["page"] == page and (not published_only or v["status"] == "PUBLISHED"):
                found = v
        return found

    def draft(self, page: str, text: str, jurisdiction: str, legal_basis: str,
              effective_date: str, review_every_days: int = 180) -> dict[str, Any]:
        prev = self.latest(page, published_only=True)
        diff = list(difflib.unified_diff((prev or {}).get("text", "").splitlines(),
                                         text.splitlines(), lineterm="", n=0))
        changed = " ".join(diff).lower()
        material = bool(prev) and any(k in changed for k in MATERIAL_SECTIONS)
        rec = {"page": page, "version": (int(prev["version"]) + 1) if prev else 1,
               "status": "DRAFT", "text": DRAFT_BANNER + text,
               "sha256": hashlib.sha256(text.encode()).hexdigest(),
               "jurisdiction": jurisdiction, "legal_basis": legal_basis,
               "effective_date": effective_date, "created_at": dt.datetime.now(dt.UTC)
               .isoformat(), "last_review": None,
               "next_review": (dt.date.today() + dt.timedelta(days=review_every_days))
               .isoformat(),
               "change_summary": diff[:200], "material_change": material,
               "user_notification_required": material,
               "renewed_consent_may_be_required": material and page in (
                   "terms_of_service", "privacy_policy", "cancellation_policy")}
        return self.versions.append(rec)

    def approve(self, page: str, reviewer: str, require_tty: bool = True) -> dict[str, Any]:
        if require_tty and not sys.stdin.isatty():
            raise PermissionError("legal pages are approved by a human reviewer at a terminal")
        if not reviewer or reviewer.startswith(("agent:", "model:")):
            raise PermissionError("a human reviewer must approve legal pages")
        cur = self.latest(page)
        if cur is None or cur["status"] != "DRAFT":
            raise ValueError("no draft to approve")
        if "[[TO FILL" in cur["text"]:
            raise ValueError("draft still has [[TO FILL]] markers")
        pub = dict(cur, status="PUBLISHED", text=cur["text"].replace(DRAFT_BANNER, "", 1),
                   last_review=dt.date.today().isoformat(), reviewed_by=reviewer)
        return self.versions.append(pub)

    def stale(self, on: dt.date | None = None) -> list[str]:
        on = on or dt.date.today()
        out = []
        for p in PAGES:
            v = self.latest(p, published_only=True)
            if v and dt.date.fromisoformat(v["next_review"]) < on:
                out.append(p)
        return out
